from pathlib import Path
import re

path = Path('legal.html')
html = path.read_text(encoding='utf-8')

entries = {
    'scope': ('Constitutional and administrative-law principles, contract law, mandatory consumer law, privacy law, and the procedural law of the forum govern interpretation and hierarchy.', 'A suspected conflict is logged, the controlling contract and mandatory law are identified, affected parties are notified where required, and the matter is escalated to the competent authority or dispute process. Emergency legal orders take priority.', 'A breach may lead to correction, suspension of the conflicting practice, contract remedies, restitution, civil damages, administrative orders, or other remedies authorized by the governing forum.'),
    'universal': ('Human-rights, equality, non-discrimination, safety, dignity, and due-process instruments and their national implementing laws govern this section.', 'The complaint is recorded, evidence is preserved, the affected person receives a fair opportunity to respond when lawful, and an impartial decision-maker assesses harm, intent, proportionality, and available defenses.', 'Confirmed misconduct may result in warning, training, removal of harmful content, access restriction, restitution, civil liability, administrative sanctions, or criminal referral where the conduct satisfies the relevant offense.'),
    'international': ('Treaties and international instruments concerning human rights, trade, anti-corruption, sanctions, customs, transport, and cross-border cooperation govern together with the implementing law of each participating State.', 'The transaction is screened by origin, destination, parties, goods, payment route, and data flow; suspicious or prohibited activity is paused; records are preserved; and required reports or referrals are made to the competent authority.', 'Consequences can include blocked or cancelled transactions, seizure, customs or sanctions enforcement, license restrictions, civil recovery, administrative fines, and criminal prosecution under applicable national implementing law.'),
    'continental': ('Regional and continental instruments, regulator decisions, market rules, competition law, consumer law, digital-services law, and regional data-protection law govern where the activity falls within their territorial scope.', 'The responsible team identifies the affected region, applies the relevant notice and response period, documents the decision, and provides the review, complaint, or regulator-access route required by that region.', 'Penalties may include corrective orders, regional administrative fines, compensation, advertising restrictions, suspension of a service, market withdrawal, or referral to national authorities.'),
    'national': ('The constitution, statutes, regulations, cases, licenses, tax rules, product-safety rules, employment rules, and criminal code of the applicable country, state, province, or locality govern the conduct.', 'Before launch or enforcement, the responsible owner records the entity, venue, license, notice, tax, and regulator requirements; after an allegation, the competent local process determines facts and provides any required hearing or appeal.', 'The competent jurisdiction may impose contractual remedies, refunds, damages, injunctions, civil or administrative fines, license action, seizure, or criminal penalties permitted by its law.'),
    'company': ('Corporate, fiduciary, accounting, tax, anti-bribery, competition, employment, securities where applicable, and records-retention laws govern company governance.', 'An allegation is assigned to an independent owner, conflicts are disclosed, records are preserved, interviews and access logs are reviewed, and the decision is documented with escalation to the board, regulator, auditor, or law-enforcement authority when required.', 'Violations may result in remediation, loss of authority, repayment, termination, director or officer liability, civil damages, regulatory orders or fines, license consequences, and criminal prosecution for qualifying conduct.'),
    'employee': ('Employment, labor, workplace-safety, anti-discrimination, wage, confidentiality, intellectual-property, data-protection, and criminal laws govern employees, contractors, and partners.', 'The report is acknowledged, retaliation is prohibited, evidence is preserved, the accused receives a fair response opportunity subject to safety and confidentiality, and the employer applies a documented, proportionate process.', 'Possible outcomes include coaching, training, warning, suspension, termination, contract claims, wage or benefit correction, civil damages, administrative penalties, professional discipline, or criminal referral.'),
    'customer': ('Consumer-protection, product-liability, contract, payment, advertising, tax, customs, seller-licensing, warranty, and commercial laws govern customer and seller conduct.', 'The listing, order, payment, delivery, identity, and communications records are compared with the complaint; the parties are given an opportunity to provide evidence; and refunds, holds, mediation, or regulator reporting are used as required.', 'A violation may result in listing removal, payment hold, refund, chargeback response, account restriction, seller suspension, restitution, civil damages, administrative penalties, product seizure, or criminal prosecution for fraud or other offenses.'),
    'user': ('Computer-misuse, fraud, harassment, privacy, intellectual-property, consumer, criminal, and civil laws govern user and visitor conduct on the service.', 'The service records the report, preserves relevant logs, applies risk-based temporary controls, verifies the allegation, gives notice or appeal where required, and refers serious or imminent threats to competent authorities.', 'Consequences may include warning, content removal, account suspension or termination, restitution, injunction, civil damages, administrative enforcement, or criminal investigation and prosecution.'),
    'operations': ('Commercial, contract, accounting, tax, competition, anti-fraud, supply-chain, product-safety, accessibility, and records laws govern business execution and practice.', 'Controls test the transaction, product, price, payment, fulfillment, and record trail; exceptions require documented approval; incidents are contained, investigated, corrected, and reported when a law requires notice.', 'Penalties and remedies may include correction, recall, refund, restitution, contract termination, damages, injunctions, administrative fines, license action, and criminal liability for knowing or reckless offenses.'),
    'ecommerce': ('Electronic-commerce, consumer-contract, advertising, pricing, payment, tax, shipping, product-safety, accessibility, privacy, and unfair-practices laws govern online sales.', 'The platform verifies required pre-contract information, consent, order confirmation, cancellation or return rights, payment records, and complaint handling; disputed transactions are preserved and reviewed before final action.', 'Misconduct may lead to corrected listings, cancelled orders, refunds, restitution, payment reversal, account or seller suspension, civil damages, consumer-agency orders, administrative fines, and criminal penalties for fraud or counterfeit activity.'),
    'instore': ('Premises-liability, accessibility, fire and building safety, health and sanitation, employment, consumer, payment, surveillance, and product-safety laws govern in-store activity.', 'An incident is made safe first, emergency services are contacted when necessary, evidence and camera records are preserved lawfully, witnesses are documented, and the responsible manager completes the required report and notice.', 'Consequences may include removal from premises, refund, repair, recall, compensation, insurance claims, civil damages, safety orders, business-license action, administrative fines, and criminal prosecution for willful or reckless harm.'),
    'creative-rights': ('Copyright, trademark, patent, design, moral-rights, publicity, cultural-heritage, licensing, and contract laws govern creative works and cultural materials.', 'A rights complaint is logged, the work and provenance are preserved, the claimant’s ownership or authorization is assessed, the affected party may respond, and lawful notice, counter-notice, takedown, restoration, or court procedures are followed.', 'Available remedies may include attribution or correction, removal, injunction, impoundment, actual damages, profits, statutory damages where authorized, costs and fees, license termination, administrative sanctions, and criminal penalties for qualifying willful infringement.'),
    'privacy': ('Privacy, data-protection, confidentiality, cybersecurity, consumer, employment, children’s-data, breach-notification, and cross-border-transfer laws govern Bonds Mall processing.', 'The controller documents purpose and legal basis, limits access, investigates incidents, records risk and affected data, notifies authorities or individuals within legally required periods, and handles data-subject requests through the prescribed channel.', 'Penalties may include correction, deletion, access restriction, compensation, audit, processing prohibition, administrative orders, regulatory fines, contractual liability, and criminal sanctions where national law creates an offense.'),
    'your-privacy': ('The applicable privacy and consumer statutes of the person’s jurisdiction govern access, correction, deletion, portability, objection, consent withdrawal, complaint, and remedy rights.', 'A request is verified proportionately, logged, answered within the statutory period, extended only when lawful and explained, and escalated to the relevant privacy regulator or court when an unresolved dispute remains.', 'Unlawful denial or misuse may result in correction, deletion, service restriction, compensation, regulator orders, administrative fines, civil damages, or other remedies available in the person’s jurisdiction.'),
    'ip': ('Copyright, patent, trademark, trade-secret, unfair-competition, database, domain-name, and trade-dress laws govern Bonds Mall intellectual property and business assets.', 'The claimant must identify the right, work or registration, allegedly infringing act, jurisdiction, and good-faith basis; Bonds Mall preserves evidence, applies notice-and-response procedures, and uses court or regulator processes for contested claims.', 'Possible remedies include takedown or restoration, injunction, seizure or destruction, actual damages and profits, statutory damages where available, costs and attorney fees, license termination, administrative orders, and criminal penalties for qualifying intentional infringement.'),
    'systems': ('Cybersecurity, computer-misuse, privacy, records, consumer, telecommunications, critical-infrastructure, and incident-reporting laws govern systems, security, and process structure.', 'Security events are triaged, contained, forensically preserved, risk-assessed, and escalated; access is reviewed; affected parties and authorities are notified when legally required; and corrective controls are tested.', 'Consequences may include credential revocation, system isolation, remediation, restitution, contract termination, civil damages, regulatory orders or fines, professional discipline, and criminal prosecution for unauthorized access, fraud, or sabotage.'),
    'enforcement': ('Administrative-procedure, civil-procedure, criminal-procedure, evidence, privacy, whistleblower, consumer, and regulator-cooperation laws govern reporting and enforcement.', 'Reports are logged, conflicts are managed, evidence is preserved lawfully, allegations are screened, parties receive proportionate notice and an opportunity to respond where required, decisions are recorded, and appeals or external referrals remain available.', 'Depending on the proven conduct and authority, outcomes may include warning, corrective action, restitution, refund, suspension, removal, injunction, civil damages, administrative fine, seizure, license action, or criminal investigation and prosecution. No penalty is imposed solely on an untested allegation.'),
}

for section_id, (laws, process, penalties) in entries.items():
    marker = f'<section class="legal-card" id="{section_id}">'
    start = html.find(marker)
    if start < 0:
        raise SystemExit(f'missing section: {section_id}')
    end = html.find('</section>', start)
    if end < 0:
        raise SystemExit(f'missing section end: {section_id}')
    block = html[start:end]
    if 'section-law-process-penalties' in block:
        continue
    basis_end = block.find('</p>', block.find('section-legal-basis'))
    if basis_end < 0:
        raise SystemExit(f'missing legal basis paragraph: {section_id}')
    insert_at = start + basis_end + len('</p>')
    panel = f'''\n            <div class="section-law-process-penalties">\n                <h3>Law, violation process, and penalties</h3>\n                <p><strong>Governing laws:</strong> {laws}</p>\n                <p><strong>Violation and penalization process:</strong> {process}</p>\n                <p><strong>Penalties and remedies:</strong> {penalties}</p>\n            </div>'''
    html = html[:insert_at] + panel + html[insert_at:]

path.write_text(html, encoding='utf-8')
print(f'updated_sections={len(entries)}')
print(f'panels={html.count("section-law-process-penalties")}')
