from pathlib import Path

path = Path('legal.html')
html = path.read_text(encoding='utf-8')

A = {
    'scope': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/ucc/1/1-301" rel="noopener noreferrer">UCC § 1-301</a> addresses territorial application of commercial law; <a href="https://supreme.justia.com/cases/federal/us/304/64/" rel="noopener noreferrer">Erie Railroad Co. v. Tompkins, 304 U.S. 64 (1938)</a> illustrates the role of forum and applicable law. These authorities do not replace the governing law of another jurisdiction.',
    'universal': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/42/2000a" rel="noopener noreferrer">42 U.S.C. § 2000a</a> prohibits specified places of public accommodation discrimination; <a href="https://supreme.justia.com/cases/federal/us/347/483/" rel="noopener noreferrer">Brown v. Board of Education, 347 U.S. 483 (1954)</a> is a leading equality and equal-protection decision. The Universal Declaration of Human Rights remains a principle source, while enforceability depends on local implementing law.',
    'international': 'Representative authorities: <a href="https://www.un.org/en/about-us/un-charter/full-text" rel="noopener noreferrer">UN Charter</a> principles and <a href="https://www.law.cornell.edu/uscode/text/50/1705" rel="noopener noreferrer">50 U.S.C. § 1705</a> illustrate international commitments and national sanctions implementation; <a href="https://law.justia.com/cases/federal/appellate-courts/F2/630/876/329923/" rel="noopener noreferrer">Filártiga v. Peña-Irala, 630 F.2d 876 (2d Cir. 1980)</a> illustrates a U.S. court’s treatment of an international human-rights claim. Application depends on treaty status and national implementation.',
    'continental': 'Representative authorities: <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng" rel="noopener noreferrer">GDPR</a> Articles 3 and 83 illustrate regional territorial scope and administrative fines; <a href="https://curia.europa.eu/juris/liste.jsf?language=en&num=C-131/12" rel="noopener noreferrer">Google Spain SL v. AEPD, C-131/12</a> illustrates regional privacy-rights enforcement. Other continental regions have different instruments and authorities.',
    'national': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/15/45" rel="noopener noreferrer">15 U.S.C. § 45</a> addresses unfair or deceptive acts in commerce; <a href="https://supreme.justia.com/cases/federal/us/593/23-109/" rel="noopener noreferrer">Axon Enterprise, Inc. v. FTC, 598 U.S. 175 (2023)</a> illustrates review of agency proceedings. The national, state, provincial, or local law of the actual transaction controls.',
    'company': 'Representative authorities (U.S. examples): <a href="https://delcode.delaware.gov/title8/c001/sc04/index.html" rel="noopener noreferrer">Delaware General Corporation Law</a> provides a corporate-governance statute; <a href="https://law.justia.com/cases/delaware/supreme-court/1996/14879.html" rel="noopener noreferrer">In re Caremark International Inc. Derivative Litigation, 698 A.2d 959 (Del. Ch. 1996)</a> is a leading oversight-duty decision. Entity-specific duties vary by incorporation jurisdiction.',
    'employee': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/42/2000e-2" rel="noopener noreferrer">42 U.S.C. § 2000e-2</a> prohibits specified employment discrimination; <a href="https://supreme.justia.com/cases/federal/us/411/792/" rel="noopener noreferrer">McDonnell Douglas Corp. v. Green, 411 U.S. 792 (1973)</a> describes a burden-shifting framework in a Title VII case. Local labor, wage, safety, and privacy law may impose additional duties.',
    'customer': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/15/45" rel="noopener noreferrer">15 U.S.C. § 45</a> addresses unfair or deceptive commerce; <a href="https://supreme.justia.com/cases/federal/us/573/102/" rel="noopener noreferrer">POM Wonderful LLC v. Coca-Cola Co., 573 U.S. 102 (2014)</a> illustrates interaction between labeling statutes and Lanham Act claims. Consumer and seller remedies vary by jurisdiction and contract.',
    'user': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/18/1030" rel="noopener noreferrer">18 U.S.C. § 1030</a> addresses specified computer-related offenses; <a href="https://supreme.justia.com/cases/federal/us/593/20-1530/" rel="noopener noreferrer">Van Buren v. United States, 593 U.S. 374 (2021)</a> interprets the Computer Fraud and Abuse Act’s access provision. Local criminal, privacy, harassment, and civil law controls other conduct.',
    'operations': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/15/1" rel="noopener noreferrer">15 U.S.C. § 1</a> addresses agreements in restraint of trade; <a href="https://supreme.justia.com/cases/federal/us/398/295/" rel="noopener noreferrer">Berkey Photo, Inc. v. Eastman Kodak Co., 603 F.2d 263 (2d Cir. 1979)</a> illustrates competition-law analysis. Commercial, safety, tax, and supply-chain statutes vary by market.',
    'ecommerce': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/15/45" rel="noopener noreferrer">15 U.S.C. § 45</a> governs unfair or deceptive commerce; <a href="https://law.justia.com/cases/federal/appellate-courts/F3/306/17/581249/" rel="noopener noreferrer">Specht v. Netscape Communications Corp., 306 F.3d 17 (2d Cir. 2002)</a> illustrates notice and assent issues in online contracting. Electronic-contract, consumer, tax, payment, and distance-selling rules differ by jurisdiction.',
    'instore': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/42/12182" rel="noopener noreferrer">42 U.S.C. § 12182</a> addresses public-accommodation discrimination; <a href="https://law.justia.com/cases/california/supreme-court/2d/69/108.html" rel="noopener noreferrer">Rowland v. Christian, 69 Cal. 2d 108 (1968)</a> is a representative premises-liability decision. Building, fire, health, accessibility, and premises laws are local and must be checked for the property.',
    'creative-rights': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/17/106" rel="noopener noreferrer">17 U.S.C. § 106</a> lists exclusive copyright rights; <a href="https://supreme.justia.com/cases/federal/us/499/340/" rel="noopener noreferrer">Feist Publications, Inc. v. Rural Telephone Service Co., 499 U.S. 340 (1991)</a> addresses originality. The <a href="https://www.wipo.int/en/web/ip-enforcement" rel="noopener noreferrer">WIPO IP-enforcement guidance</a> describes cross-border civil, administrative, border, and criminal mechanisms; local moral-rights and cultural laws may differ.',
    'privacy': 'Representative authorities: <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng" rel="noopener noreferrer">GDPR</a> provides processing, rights, cross-border, and sanction rules; <a href="https://www.ftc.gov/news-events/topics/protecting-consumer-privacy-security/privacy-security-enforcement" rel="noopener noreferrer">FTC privacy enforcement</a> describes U.S. Section 5 actions; <a href="https://supreme.justia.com/cases/federal/us/585/16-402/" rel="noopener noreferrer">Carpenter v. United States, 585 U.S. 296 (2018)</a> illustrates U.S. constitutional treatment of sensitive location data. Applicable privacy statutes depend on the person, data, controller, and place of processing.',
    'your-privacy': 'Representative authorities: <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng" rel="noopener noreferrer">GDPR Articles 12–23</a> set data-subject rights in the EU/EEA; <a href="https://www.law.cornell.edu/uscode/text/18/2710" rel="noopener noreferrer">18 U.S.C. § 2710</a> provides a U.S. video-privacy statute; <a href="https://supreme.justia.com/cases/federal/us/594/21-1496/" rel="noopener noreferrer">TransUnion LLC v. Ramirez, 594 U.S. 413 (2021)</a> addresses standing for privacy-related injury. The rights and deadlines of the person’s jurisdiction control.',
    'ip': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/35/271" rel="noopener noreferrer">35 U.S.C. § 271</a> addresses patent infringement; <a href="https://www.law.cornell.edu/uscode/text/15/1117" rel="noopener noreferrer">15 U.S.C. § 1117</a> addresses trademark remedies; <a href="https://supreme.justia.com/cases/federal/us/547/388/" rel="noopener noreferrer">eBay Inc. v. MercExchange, L.L.C., 547 U.S. 388 (2006)</a> explains that injunctions are governed by equitable principles. WIPO and TRIPS set international reference points, while national registration and remedies control.',
    'systems': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/18/1030" rel="noopener noreferrer">18 U.S.C. § 1030</a> addresses specified unauthorized computer access; <a href="https://www.ftc.gov/business-guidance/privacy-security/data-security" rel="noopener noreferrer">FTC data-security enforcement guidance</a> describes federal consumer-protection enforcement; <a href="https://supreme.justia.com/cases/federal/us/593/20-1530/" rel="noopener noreferrer">Van Buren v. United States, 593 U.S. 374 (2021)</a> limits one CFAA access theory. Cybersecurity reporting and critical-infrastructure obligations vary by sector and country.',
    'enforcement': 'Representative authorities (U.S. examples): <a href="https://www.law.cornell.edu/uscode/text/5/706" rel="noopener noreferrer">5 U.S.C. § 706</a> describes judicial review of agency action; <a href="https://supreme.justia.com/cases/federal/us/424/319/" rel="noopener noreferrer">Mathews v. Eldridge, 424 U.S. 319 (1976)</a> describes procedural due-process balancing; <a href="https://www.ftc.gov/enforcement" rel="noopener noreferrer">FTC enforcement</a> illustrates administrative and federal enforcement routes. The authority, procedure, appeal rights, and available penalties depend on the forum and offense.'
}

for section_id, authority in A.items():
    marker = f'<section class="legal-card" id="{section_id}">'
    start = html.find(marker)
    end = html.find('</section>', start)
    if start < 0 or end < 0:
        raise SystemExit(f'missing section {section_id}')
    block = html[start:end]
    if 'section-authorities' in block:
        continue
    anchor = '</div>'
    panel_start = block.find('<div class="section-law-process-penalties">')
    if panel_start < 0:
        raise SystemExit(f'missing process panel {section_id}')
    panel_end = block.find('</div>', panel_start)
    if panel_end < 0:
        raise SystemExit(f'missing panel end {section_id}')
    insert_at = start + panel_end + len('</div>')
    html = html[:insert_at] + f'\n            <p class="legal-footer-note section-authorities"><strong>Representative statutes and case law:</strong> {authority} These are illustrative authorities, not a statement that they govern every market or transaction.</p>' + html[insert_at:]

path.write_text(html, encoding='utf-8')
print(f'authority_blocks={html.count("section-authorities")}')
