/* Bonds Mall Resubmission Flow — verified health failure -> deduplicated recovery queue. */
(function(){'use strict';
 const PLATFORMS=['Craigslist','AdLandPro','ClassifiedAds','Facebook Marketplace','OfferUp','Mercari','Poshmark','Nextdoor','eBay','Etsy'];
 const state={ads:[],broken:[],checkedAt:null,scanning:false};
 const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function getSellerDocument(){if(document.title&&/seller/i.test(document.title))return document;return null;}
 async function fetchSellerHtml(){const local=getSellerDocument();if(local)return local;const r=await fetch('seller.html',{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error('seller.html could not be loaded ('+r.status+').');return new DOMParser().parseFromString(await r.text(),'text/html');}
 function looksLikeAdUrl(url){try{const u=new URL(url,location.href);if(!/^https?:$/.test(u.protocol)||/^(localhost|127\.0\.0\.1)$/i.test(u.hostname))return false;return /(craigslist|adlandpro|classifiedads|facebook|marketplace|offerup|mercari|poshmark|nextdoor|ebay|etsy|listing|classified|ad[-_]?id|product)/i.test(u.hostname+u.pathname+u.search);}catch(_){return false;}}
 function inferPlatform(url){const h=new URL(url).hostname.toLowerCase();if(h.includes('craigslist'))return'Craigslist';if(h.includes('adlandpro'))return'AdLandPro';if(h.includes('classifiedads'))return'ClassifiedAds';if(h.includes('facebook'))return'Facebook Marketplace';if(h.includes('offerup'))return'OfferUp';if(h.includes('mercari'))return'Mercari';if(h.includes('poshmark'))return'Poshmark';if(h.includes('nextdoor'))return'Nextdoor';if(h.includes('ebay'))return'eBay';if(h.includes('etsy'))return'Etsy';return'Unknown';}
 function findValue(root,names){const text=root.textContent||'';for(const name of names){const re=new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*[:=-]\\s*([^\\n|]+)','i');const m=text.match(re);if(m)return m[1].trim();}return'';}
 function extractAds(doc){const ads=[];[...doc.querySelectorAll('a[href]')].forEach((a,index)=>{if(!looksLikeAdUrl(a.href))return;const root=a.closest('[data-product],[data-ad],[data-listing],article,tr,li,.ad,.listing,.product')||a.parentElement||a;ads.push({id:'seller-ad-'+index,url:a.href,product:(a.dataset.product||root.dataset?.product||root.dataset?.productName||findValue(root,['product','productName','item','title'])||a.textContent.trim()||'Unknown product').slice(0,240),location:(a.dataset.location||root.dataset?.location||root.dataset?.city||findValue(root,['location','city','market','state'])||'Unknown location').slice(0,240),platform:inferPlatform(a.href)});});const sources=[window.BondsMall&&window.BondsMall.activeAds,window.BondsMallActiveAdsRegistry&&window.BondsMallActiveAdsRegistry.list?window.BondsMallActiveAdsRegistry.list():null];sources.forEach(source=>{if(!Array.isArray(source))return;source.forEach((ad,index)=>{const url=ad&&(ad.url||ad.liveUrl);if(!looksLikeAdUrl(url))return;ads.push({id:ad.id||'record-'+index,url,product:ad.product||ad.title||'Unknown product',location:ad.location||'Unknown location',platform:ad.platform||inferPlatform(url)});});});return ads.filter((ad,i,all)=>all.findIndex(x=>x.url===ad.url)===i);}
 async function checkUrl(url){const endpoint=window.BONDS_MALL_URL_STATUS_ENDPOINT||localStorage.getItem('bondsMallUrlStatusEndpoint');if(endpoint){const r=await fetch(endpoint+(endpoint.includes('?')?'&':'?')+'url='+encodeURIComponent(url),{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error('URL status service returned '+r.status);const x=await r.json();return{live:x.status===200||x.live===true,status:x.status||null,finalUrl:x.url||url};}const target=new URL(url,location.href);if(target.origin!==location.origin)return{live:false,status:null,error:'Cross-origin URL requires BONDS_MALL_URL_STATUS_ENDPOINT.'};let r;try{r=await fetch(target.href,{method:'HEAD',cache:'no-store',redirect:'follow',credentials:'same-origin'});}catch(_){r=null;}if(!r||r.status===405||r.status===501)r=await fetch(target.href,{method:'GET',cache:'no-store',redirect:'follow',credentials:'same-origin'});return{live:!!r&&r.status===200,status:r?r.status:null,finalUrl:r?r.url:url};}
 async function scan(){if(state.scanning)return state;state.scanning=true;setStatus('Scanning seller.html for live product-ad URLs…');try{const doc=await fetchSellerHtml();state.ads=extractAds(doc);state.broken=[];for(const ad of state.ads){try{const result=await checkUrl(ad.url);ad.status=result.status;ad.finalUrl=result.finalUrl;ad.live=result.live;if(!result.live)state.broken.push(Object.assign({},ad,{reason:result.error||('HTTP '+(result.status||'unreachable'))}));}catch(error){ad.live=false;ad.status=null;state.broken.push(Object.assign({},ad,{reason:error.message}));}}state.checkedAt=new Date().toISOString();render();setStatus('Scan complete: '+state.ads.length+' ad URL(s), '+state.broken.length+' requiring resubmission.');window.dispatchEvent(new CustomEvent('bonds:resubmission-scan-complete',{detail:getState()}));}finally{state.scanning=false;}return state;}
 function render(){const host=document.querySelector('[data-resubmission-list]')||document.querySelector('#resubmissionList');if(!host)return;if(!state.broken.length){host.innerHTML='<div class="empty">No non-live product ads found.</div>';return;}host.innerHTML=state.broken.map(ad=>'<article class="resubmission-item"><strong>'+esc(ad.product)+'</strong><div>'+esc(ad.location)+'</div><div>'+esc(ad.platform)+'</div><div class="reason">'+esc(ad.reason)+'</div><div class="url">'+esc(ad.url)+'</div><button type="button" data-resubmit="'+esc(ad.id)+'">Add to resubmission queue</button></article>').join('');host.querySelectorAll('[data-resubmit]').forEach(b=>b.addEventListener('click',()=>queueForResubmission(b.dataset.resubmit)));}
 function queueForResubmission(id){const ad=state.broken.find(x=>x.id===id);if(!ad)return;const q=window.BondsMallMissionJobQueue;if(q){const job=q.enqueue({missionId:'RESUBMISSION',product:ad.product,location:ad.location,productId:ad.productId,locationId:ad.locationId,platform:ad.platform,sourceUrl:ad.url,priority:'P1',status:'queued',resubmission:true,resubmissionReason:ad.reason});window.dispatchEvent(new CustomEvent('bonds:resubmission-queued',{detail:job}));setStatus('Queued '+ad.product+' / '+ad.location+' for controlled resubmission.');return;}const key='bondsMallResubmissionQueue';let queue=[];try{queue=JSON.parse(localStorage.getItem(key)||'[]');}catch(_){}if(!queue.some(x=>x.sourceUrl===ad.url&&x.platform===ad.platform))queue.push({product:ad.product,location:ad.location,platform:ad.platform,sourceUrl:ad.url,queuedAt:new Date().toISOString(),status:'ready-for-resubmission',reason:ad.reason});localStorage.setItem(key,JSON.stringify(queue));window.dispatchEvent(new CustomEvent('bonds:resubmission-queued',{detail:ad}));setStatus('Added '+ad.product+' / '+ad.location+' to the resubmission queue.');}
 function setStatus(message){const el=document.querySelector('[data-resubmission-status]')||document.querySelector('#resubmissionStatus');if(el)el.textContent=message;}
 function getState(){return JSON.parse(JSON.stringify(state));}
 window.BondsMallResubmission={scan,getState,queueForResubmission,platforms:PLATFORMS};window.addEventListener('DOMContentLoaded',scan);
})();
